#
# Blog Settings
#
author: Yaobin "Robin" Wen
description: Yaobin's Blog
url: http://yaobinwen.github.io
title: Yaobin
gravatar_url: https://avatars0.githubusercontent.com/u/6106393?v=3&s=460
favicon: https://avatars0.githubusercontent.com/u/6106393?v=3&s=460

# Github repositories
github_user: yaobinwen
github_repo_url: https://github.com/yaobinwen/yaobinwen.github.io

# Email
email: robin.wyb@gmail.com

# Linkedin
linkedin_user: yaobinwen

# Stack Overflow
stackoverflow_user: 630364/yaobin?tab=profile

# Disqus Comments
disqus_short_name: yaobinwengithubio
disqus_show_comment_count: true

# Google Analytics
# google_analytics_tracking_id: UA-177588-1


#
# Jekyll Settings
#
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
